### ISSUE TITLE
Crashing on calling  mSheetLayout.expandFab();

### ISSUE THREAD

**Issue by atul7398** [coyarzun89/FabTransitionActivity#10]
Logcat error stacktrace

02-01 19:16:40.595 9254-9254/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.NoSuchMethodError: io.codetail.animation.SupportAnimator.setDuration
                                                     at com.github.fabtransitionactivity.SheetLayout.expandPreLollipop(SheetLayout.java:250)
                                                     at com.github.fabtransitionactivity.SheetLayout.expandFab(SheetLayout.java:185)
                                                     at com.example.atul.gmailapp.MainActivity.onFabClick(MainActivity.java:85)
                                                     at com.example.atul.gmailapp.MainActivity$1.onClick(MainActivity.java:65)
                                                     at android.view.View.performClick(View.java:4211)
                                                     at android.view.View$PerformClick.run(View.java:17267)
                                                     at android.os.Handler.handleCallback(Handler.java:615)
                                                     at android.os.Handler.dispatchMessage(Handler.java:92)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:4898)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by ansalali** [comment]
you need to change 

```
compile ('com.github.ozodrukh:CircularReveal:1.3.1@aar') {
        transitive = true;
    }
```

to 

```
compile ('com.github.ozodrukh:CircularReveal:1.1.1@aar') {
        transitive = true;
    }
```

for me after that everything works fine
